sudo: required
dist: bionic
language: generic

install:
  - cd third-party && ./build_third_party.sh && cd -
  - mkdir -p build && cd build
  - cmake -DBUILD_TESTS=ON .. 
  - cmake --build . --target all

notifications:
  email:
    on_success: never
    on_failure: always
script:
  - ./build/test/TestDataFileGenerator test-data/TestDataFile 5242880
  - GTEST_COLOR=1 ctest --output-on-failure
