sudo: required
dist: bionic
language: generic

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - cd third-party && ./build_third_party.sh && cd -
  - g++ test-data/fileGenerator.cpp -o test-data/fileGenerator
  - g++ test-data/fileGenerator.cpp -o test-data/fileGenerator
  - mkdir -p build && cd build
  - cmake --build . --target all

notifications:
  email:
    on_success: never
    on_failure: always
script:
  - ./test-data/fileGenerator test-data/TestDataFile 5242880
  - ./build/MultisetChunkTest
  - ./build/MultisetDataProviderTest
